[workspace]
resolver = "2"
members = [
  "crates/solar_sonar",
  "crates/solar_sonar_dev",
]
default-members = ["crates/solar_sonar"]

[workspace.dependencies]
bzip2 = "0.6"
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
const_format = "0.2"
directories = "6"
encoding_rs_io = "0.1"
encoding_rs = "0.8"
heck = "0.5"
itertools = "0.14.0"
ouroboros = "0.18"
ort-sys = { version = "=2.0.0-rc.9", default-features = false } # pinned for piper
piper-rs = "0.1"
pretty_assertions = "1.4"
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.10"
reqwest = { version = "0.13", features = ["blocking"] }
rodio = { version = "0.21" }
ron = "0.12"
rusqlite = "0.38"
serde = { version = "1", features = ["derive"] }
shellexpand = { version = "3", features = ["path"] }
snafu = "0.8"
tokio = { version = "1.4", features = ["full" ] }
syn = "2"
tar = "0.4"
toml = "1"

