[package]
name = "solar_sonar"
version = "0.2.0"
edition = "2024"
description = "StarMap alerts for EVE Online"
authors = ["cornmonger <cormonger@cornmonger.fish>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/cornmonger/solar_sonar"
homepage = "https://cornmonger.fish"
categories = []
keywords = ["solar", "sonar", "eve"]

[dependencies]
bzip2.workspace = true
clap.workspace = true
chrono.workspace = true
const_format.workspace = true
directories.workspace = true
encoding_rs_io.workspace = true
encoding_rs.workspace = true
heck.workspace = true
itertools.workspace = true
ouroboros.workspace = true
ort-sys.workspace = true
piper-rs.workspace = true
rand.workspace = true
reqwest.workspace = true
rodio.workspace = true
serde.workspace = true
shellexpand.workspace = true
snafu.workspace = true
tar.workspace = true
tokio.workspace = true
toml.workspace = true
indexmap = "2.13.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }

[dev-dependencies]
pretty_assertions.workspace = true

